import Head from 'next/head';
import React from 'react';
import { Footer } from './Footer';
import { Nav } from './Nav';

export const Layout: React.FC = ({ children }) => {
    return (
        <>
            <Head>
                <title>Super Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <div className="flex flex-col h-screen">
                <main className="mb-auto flex-grow">
                    {children}
                </main>
                <Footer />
            </div>
        </>
    )
}