name: Open an Issue Using a Blank Form
description: Open a new issue using a blank form
title: "[Issue] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our site!
  - type: textarea
    id: issue-body
    attributes:
      label: What is the issue about?
      description: Describe the issue as much as possible.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/lealceldeiro/org.wcdevs.blog.front/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
